[package]
name = "day-24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigfloat = "1.7.0"
z3 = "0.12"
z3-sys = "0.8.1"
